version: '2.27.0'
services:
  api_redeco:
    container_name: api-redeco
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    restart: always

  nginx:
    container_name: nginx-container
    image: nginx:1.25.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/condusef.gob.mx.crt:/condusef.gob.mx.crt
      - ./nginx/condusef.gob.mx.key:/condusef.gob.mx.key
    ports:
      - "443:443"
    depends_on:
      - api_redeco
    restart: always
